services:
  web:
    build: .
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    environment:
      - PROJECT_NAME=FastAPI Web App
      - DEFAULT_LAYOUT=default
      - DEFAULT_NAVBAR=top_fixed
      # Add other environment variables here
    restart: always